Ready for pickup email
hotwax/oms-documentation pull request #12
Opened 2023-06-21 08:32 UTC by Dhiraj1405

2023-06-21 08:33 UTC, Dhiraj1405 commented
@dt2patel Please review and let me know the changes

2023-07-05 13:53 UTC, Dhiraj1405 commented
Closes issue #18

2023-07-28 05:22 UTC, dt2patel requested changes
Added some suggestions and questions. Once resolved we can merge this

2023-07-28 05:22 UTC, dt2patel commented on Journeys/Email integration/Ready for pickup email.md
> +| `setPackedOnly`        | A flag indicating if the shipment should be packed. Default value is 'Y' if not specified.  |    Yes   |
```suggestion
| `setPackedOnly`        | A flag indicating if the shipment should only be packed. If the customer is going to pickup their order at the fulfillment location, then this should be enabled to prevent the order from being marked as shipped. Default value is 'Y' if not specified.  |    Yes   |
```

2023-07-28 05:22 UTC, dt2patel commented on Journeys/Email integration/Ready for pickup email.md
> +When store staff pack the order items and indicate their readiness for pickup, the `quickShipEntireShipGroup` API converts the order items into a shipment and marks them packed in the OMS
```suggestion
When store staff pack the order items and indicate their readiness for pickup, the `quickShipEntireShipGroup` API creates a shipment from the selected shipgroup and moves it to the "Packed" status.
```

2023-07-28 05:22 UTC, dt2patel commented on Journeys/Email integration/Ready for pickup email.md
> +### Step 2: Trigger `sendReadyToPickupItemNotification` chained event condition action
```suggestion
### Step 2: Trigger `sendReadyToPickupItemNotification` chained event condition action service
```

If this is the service them then we should be clear that this is called by the event condition action. Then below we should also mention that developers are calling this service not the eca.

2023-07-28 05:22 UTC, dt2patel commented on Journeys/Email integration/Ready for pickup email.md
> +The order type filters `Store pickup` and `Ship to store` orders to send the email. The configuration determines the system responsible for sending the email and data required to configure email cont
```suggestion
The chained service works for both `Store pickup` and `Ship to store` shipments. Emails are triggered when `Store pickup` shipments are moved to packed status and `Ship to store `shipments are moved to "scheduled" status. The system responsible for sending the email and order details is configured in the following Product Store setting. 
```

2023-07-28 11:19 UTC, Dhiraj1405 commented
Have made the suggested changes., please merge @dt2patel

2023-07-28 11:53 UTC, dt2patel approved these changes

2023-07-28 11:53 UTC, merged