Plugins and perform find api
hotwax/oms-documentation pull request #15
Opened 2023-07-02 07:34 UTC by Dhiraj1405

2023-07-05 13:58 UTC, Dhiraj1405 commented
Closes #20

2023-07-28 06:01 UTC, dt2patel requested changes
Added comments and suggestions. Mostly looks good though

2023-07-28 06:01 UTC, dt2patel commented on Perform find.md
> -#### Example
we have a video about how to use perform find, check if its relevant and attach it here if that makes sense.

2023-07-28 06:01 UTC, dt2patel commented on Plugins/Display app version with @hotwax-app-version-info package.md
> +The App version info package is a software package developed by HotWax Commerce that provides functionality to retrieve version information of an application. By using this package, HotWax fetches an
```suggestion
The App version info package is a software package developed by HotWax Commerce that provides functionality to retrieve version information of an application. Using this package helps with monitoring and displaying version information within the application's user interface for troubleshooting errors and bugs faced on certain versions of an app.
```

2023-07-28 06:01 UTC, dt2patel commented on Plugins/Manage app styling with @hotwax-apps-theme package.md
> +The Apps theme package is a software library developed by HotWax Commerce that provides styling functionalities for applications. By using this package, HotWax enhances the visual appearance and user
```suggestion
The Apps theme package is a software library developed by HotWax Commerce to deploy a consistent set of styles for all apps from a centrally managed style package. Global styles and branding overrides are managed from here and then imported into all apps.
```

2023-07-28 06:01 UTC, dt2patel commented on Plugins/Save files with FileSaver package.md
> +When retailers generate their shipping labels outside of HotWax, they need to export all packed orders once and share it with carrier partner to generate shipping labels and give tracking codes. The
```suggestion
When retailers generate their shipping labels outside of HotWax, they need to export all packed orders once and share it with carrier partner to generate shipping labels and give tracking codes. The FileSaver package helps the user quickly save the file in their systems with their desired name.
```

2023-07-28 10:34 UTC, Dhiraj1405 commented on Perform find.md
> -#### Example
sure adding

2023-07-28 10:37 UTC, Dhiraj1405 commented
Made suggested changes. Please merge @dt2patel

2023-07-28 11:00 UTC, merged