Update: The Product identifier steps for gorjana.
hotwax/oms-documentation pull request #507
Opened 2024-05-27 06:25 UTC by aniket12chouhan

Update: product management strategy to include steps for changing SKU settings for Shopify integration

2024-07-02 05:41 UTC, janvi04 requested changes

2024-07-02 05:41 UTC, janvi04 commented on gorjana/flows/products/README.md
> +gorjana's uses `SKU` as their primary product identifier. Before syncing products from Shopify, make sure to change this settings in the Product Store.
gorjana uses 'Shopify Product SKU' as their primary product identifier. Before syncing products from Shopify, make sure to change this setting in the Product Store.

2024-07-02 05:41 UTC, janvi04 commented on gorjana/flows/products/README.md
> +Steps to change Product Store:
Steps to change Product Store Settings

2024-07-02 05:41 UTC, janvi04 commented on gorjana/flows/products/README.md
> +1. Navigate to the Product Store detail page
Navigate to the Product Stores page under Settings.

2024-07-19 07:28 UTC, dt2patel approved these changes

2024-07-19 07:28 UTC, merged