HotWax commerce system architecture
hotwax/oms-documentation pull request #681
Opened 2024-07-15 05:41 UTC by AjinkyaM1

HotWax commerce system architecture

2024-08-01 15:12 UTC, dt2patel requested changes

2024-08-01 15:12 UTC, dt2patel commented on deployment&configuration/architecture/README.md
> +![AWS](https://github.com/user-attachments/assets/c0c6637e-10e7-4a99-87de-b7bb126510e1)
Please use a local file reference instead of HTTPS reference in this scenario. @AjinkyaM1

2024-08-02 05:42 UTC, AjinkyaM1 commented on deployment&configuration/architecture/README.md
> +![AWS](https://github.com/user-attachments/assets/c0c6637e-10e7-4a99-87de-b7bb126510e1)
Done

2024-08-02 05:43 UTC, dt2patel approved these changes

2024-08-02 05:43 UTC, merged