Extended the description in the incoming shipment creation flow
hotwax/oms-documentation pull request #919
Opened 2024-11-22 09:55 UTC by Chinmay2107

2024-12-06 23:12 UTC, toaditi requested changes
There are a few edits that will bring this document up to date. Added comments accordingly.

2024-12-06 23:12 UTC, toaditi commented on mephisto/Requirements/Transfer_Order_Flows/Create_Corr_Transfer_In_Ship.md
>     - **Note**: The format of this file needs to be identified. Ideally, it should match the format used by the existing jobs. This is JSON
I think line can also be deleted.

2024-12-06 23:12 UTC, toaditi commented on mephisto/Requirements/Transfer_Order_Flows/Create_Corr_Transfer_In_Ship.md
>     - A NiFi flow will be created to process the files placed at the SFTP location.
The NiFi has been created and tested. Details of the flow should be added here.

2024-12-06 23:12 UTC, toaditi commented on mephisto/Requirements/Transfer_Order_Flows/Create_Corr_Transfer_In_Ship.md
> +The following JOLT transformation is used to create the new `"IN_TRANSFER"` shipment:
This is a part of the NiFi flow.

2026-07-12 21:24 UTC, dt2patel commented on mephisto/Requirements/Transfer_Order_Flows/Create_Corr_Transfer_In_Ship.md
>     - **Note**: The format of this file needs to be identified. Ideally, it should match the format used by the existing jobs. This is JSON
This thread is outdated. The current PR has no visible diff at this location, so there is no verified line to remove.

2026-07-12 21:24 UTC, dt2patel commented on mephisto/Requirements/Transfer_Order_Flows/Create_Corr_Transfer_In_Ship.md
>     - A NiFi flow will be created to process the files placed at the SFTP location.
Evidence gap: please provide the Mephisto NiFi flow identifier or client-approved technical source that proves the trigger, transformed fields, and expected result. The issue and current PR do not establish those details, so I cannot add a generic substitute.

2026-07-12 21:24 UTC, dt2patel commented on mephisto/Requirements/Transfer_Order_Flows/Create_Corr_Transfer_In_Ship.md
> +The following JOLT transformation is used to create the new `"IN_TRANSFER"` shipment:
Evidence gap: please provide the Mephisto NiFi flow identifier or client-approved technical source that proves this step and its role in the transfer-in shipment flow. The current PR does not establish it.

2026-07-18 15:29 UTC, merged