Customer owned frame orders process documentation
hotwax/oms-documentation pull request #936
Opened 2024-12-05 05:10 UTC by AjinkyaM1

This document will provide the current process and the solution to enhance the process of handling the customer owned frame orders

2024-12-05 11:57 UTC, dt2patel requested changes
One small change

2024-12-05 11:57 UTC, dt2patel commented on krewe/Flows/SalesOrders/customer-owned-frame.md
> +When a customer wants to change the lenses in their pre-owned frame, we can use the same HotWax admin helper to add a custom line item property.
Don't use first person language

2024-12-05 13:23 UTC, AjinkyaM1 commented on krewe/Flows/SalesOrders/customer-owned-frame.md
> +When a customer wants to change the lenses in their pre-owned frame, we can use the same HotWax admin helper to add a custom line item property.
Sure, I will keep that in mind.

2025-01-08 02:16 UTC, dt2patel requested changes

2025-01-08 02:16 UTC, dt2patel commented on krewe/Flows/SalesOrders/customer-owned-frame.md
> +   - For customer-owned frames, a custom line item property will be added. This allows us to link the pre-owned frame to the lens product they are purchasing. In shopify the lens product will be visi
```suggestion
   - For customer-owned frames, a custom line item property will be added. This allows us to link the pre-owned frame to the lens product they are purchasing. In Shopify the lens product will be visible as a line item and the customer owned frame will be added in the line item property of the order JSON. 
```

2025-01-08 02:16 UTC, dt2patel approved these changes

2025-01-08 02:17 UTC, merged